### ISSUE TITLE
Enable commit of generated include configs into projects

### ISSUE THREAD

**Issue by MrHash** [honeybee/honeybee#30]
There are absolute paths in the type maps and and xml files which need to be removed in order to enable committing of generated configs

**Comment by shrink0r** [comment]
@graste What you think. Guess this would be a nice step towards an easier deployable system.

**Comment by graste** [comment]
With all paths being relative this should work and make the system of includes more transparent. When you add/remove types the changes will not be hidden by gitignore anymore. I don't know whether there are things to take into account apart from the paths though. We get closer to a working working copy after checkout/clone with this, so: :+1:
