### ISSUE TITLE
Error when saving a referenced entity inside an embedded entity

### ISSUE THREAD

**Issue by samir-plusb** [honeybee/honeybee#54]
I created an entity "X" which has an embedded entity "RelationToX", which has a field that references the Entity "X" again. There were no problems in the last days, but suddenly an error occurs every time the created/modified entity is saved. The following error occurs: 

```
Notice: Undefined property: Honeybee\Model\Command\EmbeddedEntityCommandBuilder::$entity in /srv/www/welcome-app.local/vendor/honeybee/honeybee/src/Model/Command/EmbeddedEntityCommandBuilder.php on line 65
```

I made a bugfix, which solves my case and I will create a pull request. You have to evaluate this please...

**Comment by MrHash** [comment]
This is just a notice right? Changing this doesn't affect any behaviour?
