### ISSUE TITLE
Get rid of hardcoded write event names

### ISSUE THREAD

**Issue by shrink0r** [honeybee/honeybee#63]
see: https://github.com/honeybee/honeybee/blob/74dbe8ca7256bfb8248956605d4990d2cdcd4ccb/src/Projection/WorkflowSubject.php#L78

**Comment by graste** [comment]
See https://github.com/honeybee/honeybee/blob/workflowservice/src/Infrastructure/Workflow/WorkflowService.php#L114-L118 from #67

**Comment by graste** [comment]
They are now configurable via config instead of completely hardcoded. This was done while working on #67 – see https://github.com/honeybee/honeybee/blob/515631fd487b40a9d473543242f3a8c9ade90e1b/src/Infrastructure/Workflow/WorkflowService.php#L115-L118
