### ISSUE TITLE
Command & Event type prefix inconsistency

### ISSUE THREAD

**Issue by MrHash** [honeybee/honeybee#76]
`Command` and `AggregateRootEvent` return a `strtolower`'d vendor prefix whereas in most other places it is a snake case. Command bus configuration and event bus matching expressions will need to be updated.

**Comment by MrHash** [comment]
ref ca8dffae5f4fa2ede3bb7d1c539a80ed1ce67a0b, 9fa701763529c7323ba89c5d3a1a14f4177d8299

**Comment by shrink0r** [comment]
@MrHash nice catch 👍 
I think we can close this now, yes?

**Comment by MrHash** [comment]
i believe so. It breaks BC for me so i have to modify my configs tho

**Comment by graste** [comment]
@shrink0r Do we need to change something in the agavi-cmf and projects w/ this change?
