### ISSUE TITLE
Introduce an Environment interface for binding to users/session of frameworks

### ISSUE THREAD

**Issue by shrink0r** [honeybee/honeybee#8]
So we can bind framework specific user/session impls to the honeybee core we need an interface that may be used within frameworks accordingly.
Pls implement within honeybee:
- EnvironmentInterface

and within the vendor-cmf:
- deffault impl for the EnvironmentInterface
- EnvironmentProvisioner within the honeybee-agavi-vendor-cmf that passes the AclSecurityUser

**Comment by MrHash** [comment]
Ref 582c4145f982ca2a2e7a9d1e84cda6aaf1e20fab
