### ISSUE TITLE
RelationProjectionUpdater OOM for non-referenced projection type

### ISSUE THREAD

**Issue by graste** [honeybee/honeybee#82]
The RelationProjectionUpdater runs a scroll query for a type that isn't referenced anywhere when a ProjectionUpdatedEvent for that type arrives. It seems, that the empty check for the reference-filter-list doesn't work correctly.

**Comment by MrHash** [comment]
https://github.com/honeybee/honeybee/blob/16d2217e36dff6f81ff8842d96d0d8f16a4d8114/src/Projection/EventHandler/RelationProjectionUpdater.php#L183

yup that probably a bug as `CriteriaList` is never considered empty.
