### ISSUE TITLE
RelationProjectionUpdater for too many referenced entities goes OOM

### ISSUE THREAD

**Issue by graste** [honeybee/honeybee#83]
The event hander uses the ``ProjectionQueryService::scroll()`` method, but holds everything found in memory. This breaks for scenarios where you e.g. reference tags everywhere and then rename one tag name. :-)
There are multiple solutions which might be non-breaking etc. But the agreed solution is to break the behaviour of the scroll method to not give one projection after another to the provided callback, but provide the complete `FinderResult`. This allows people to check the total result and do bulk stuff immediately instead of aggregating the results again to do that. The `scroll` method was implemented that way to behave similar to the `walk` method. We figure that this is not necessary anymore.

**Comment by MrHash** [comment]
While I don't mind the solution, the `scroll` implementation is not really the problem, since AFAICS it's easy enough to manage the iterated results in your own callback, such as by doing batch operations. I'd suggest fixing #52 #82 before deciding on the scrolling behaviour..

**Comment by graste** [comment]
We will not break the implementation. The scroll BC would be nice when no total count would've been available. I will try to change the RelationProjectionUpdater without a change to the scroll method. That should be sufficient.

**Comment by graste** [comment]
Ping @MrHash @shrink0r – updated the RelationProjectionUpdater, decreased limit to 100 and tests are still running.

**Comment by MrHash** [comment]
Out of interest, was it OOM with the bigger batch size?

**Comment by graste** [comment]
Yes. Regardless it would use scroll to put potentially thousands of entities in memory.
